### ISSUE TITLE
No documentation for plugs

### ISSUE THREAD

**Issue by KiTTYsh** [copygirl/cord#3]
There is a significant lack of documentation for what configuration options are to be used for plugs and stored in config.json.  There is currently information for sockets (auth.json) in the wiki, but without documentation for plugs (specifically the Bridge plug), the project cannot be used for it's intended purpose without figuring it out from the code, by yourself.

**Comment by copygirl** [comment]
Ahh! The one reason I don't like open sourcing projects for: Can't just let it die.

cord has its issues. One of the big reasons I decided to stop working on it is the fact that it currently can't properly support Discord nicknames. There's only one object for each Discord user used across multiple servers, but they can have a different nickname on each server. I'll try to fix your two reported issues though.

**Todo:**
- [x] [Logging](https://github.com/copygirl/cord/wiki/Plug:-Logging)
- [x] [Respawn](https://github.com/copygirl/cord/wiki/Plug:-Respawn)
- [x] [Bridge](https://github.com/copygirl/cord/wiki/Plug:-Logging)
- [x] [React](https://github.com/copygirl/cord/wiki/Plug:-React)

**Comment by copygirl** [comment]
Right, here we go. Even included some information on how to create [custom commands](https://github.com/copygirl/cord/wiki/Plug:-React#custom-commands). That should be sufficient to close this issue, right?
